name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'The type of version bump to apply (major, minor, or patch)'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch
      prerelease:
        description: 'Whether this is a pre-release'
        required: true
        default: false
        type: boolean

jobs:
  test:
    uses: ./.github/workflows/testing.yml

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Install cargo-edit
        run: cargo install cargo-edit --locked

      - name: Bump version
        run: cargo set-version --workspace --bump ${{ github.event.inputs.version_type }}

      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep -m 1 '^version = ' Cargo.toml | cut -d '"' -f 2)
          echo "new_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        run: |
          git commit -am "chore: bump version to ${{ steps.get_version.outputs.new_version }}"
          git push

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: v${{ steps.get_version.outputs.new_version }}
        run: |
          PRERELEASE_FLAG=""
          if [[ "${{ github.event.inputs.prerelease }}" == "true" ]]; then
            PRERELEASE_FLAG="--prerelease"
          fi
          gh release create "$TAG_NAME" \
            --title "Release $TAG_NAME" \
            --generate-notes \
            $PRERELEASE_FLAG
